CREATE TABLE TIPO_LOGRADOURO(
	CODIGO_TLOG INT PRIMARY KEY IDENTITY,
	TIPO_LOG VARCHAR(20) NOT NULL
)
GO
CREATE TABLE LOGRADOURO(
	CODIGO_LOG INT PRIMARY KEY IDENTITY,
	LOGRADOURO VARCHAR(100) NOT NULL
)
GO
CREATE TABLE BAIRRO(
	CODIGO_BAIRRO INT PRIMARY KEY IDENTITY,
	BAIRRO VARCHAR(50) NOT NULL
)
GO
CREATE TABLE MUNICIPIO(
	CODIGO_MUN INT PRIMARY KEY IDENTITY,
	MUNICIPIO VARCHAR(50) NOT NULL
)
GO
CREATE TABLE ESTADO(
	CODIGO_ESTADO INT PRIMARY KEY IDENTITY,
	ESTADO VARCHAR(50) NOT NULL,
	SIGLA_ESTADO CHAR(2) NOT NULL
)
GO
CREATE TABLE DOMICILIO(
	CODIGO_DOM INT PRIMARY KEY IDENTITY,
	CODIGO_TIPO_LOG_DOM INT,
	CODIGO_LOG_DOM INT,
	CODIGO_BAIRRO_DOM INT,
	CODIGO_MUNI_DOM INT,
	CODIGO_ESTADO_DOM INT,
	
	NUMERO INT NOT NULL,
	
	CONSTRAINT FK_TL_DOM		FOREIGN KEY(CODIGO_TIPO_LOG_DOM)	REFERENCES TIPO_LOGRADOURO(CODIGO_TLOG),
	CONSTRAINT FK_LOG_DOM		FOREIGN KEY(CODIGO_LOG_DOM)			REFERENCES LOGRADOURO(CODIGO_LOG),
	CONSTRAINT FK_BAIRRO_DOM	FOREIGN KEY(CODIGO_BAIRRO_DOM)		REFERENCES BAIRRO(CODIGO_BAIRRO),
	CONSTRAINT FK_MUNI_DOM		FOREIGN KEY(CODIGO_MUNI_DOM)		REFERENCES MUNICIPIO(CODIGO_MUN),
	CONSTRAINT FK_ESTADO_DOM	FOREIGN KEY(CODIGO_ESTADO_DOM)		REFERENCES ESTADO(CODIGO_ESTADO)
)
GO

INSERT INTO TIPO_LOGRADOURO(TIPO_LOG)
VALUES
('ACAMPAMENTO'),('ACESSO'),('ADRO'),('AEROPORTO'),('ALAMEDA'),('ALTO'),('AREA'),('AREA ESPECIAL'),('ARTERIA'),('ATALHO'),('AVENIDA'),('AVENIDA CONTORNO'),
('BAIXA'),('BALAO'),('BALNEARIO'),('BECO'),('BELVEDERE'),('BLOCO'),('BOSQUE'),('BOULEVARD'),('BURACO'),('CAIS'),('CALCADA'),('CAMINHO'),('CAMPO'),
('CANAL'),('CHACARA'),('CHAPADAO'),('CIRCULAR'),('COLONIA'),('COMPLEXO VIARIO'),('CONDOMINIO'),('CONJUNTO'),('CORREDOR'),('CORREGO'),('DESCIDA'),
('DESVIO'),('DISTRITO'),('ELEVADA'),('ENTRADA PARTICULAR'),('ENTRE QUADRA'),('ESCADA'),('ESPLANADA'),('ESTACAO'),('ESTACIONAMENTO'),('ESTADIO'),
('ESTANCIA'),('ESTRADA'),('ESTRADA MUNICIPAL'),('FAVELA'),('FAZENDA'),('FEIRA'),('FERROVIA'),('FONTE'),('FORTE'),('GALERIA'),('GRANJA'),('HABITACIONAL'),
('ILHA'),('JARDIM'),('JARDINETE'),('LADEIRA'),('LAGO'),('LAGOA'),('LARGO'),('LOTEAMENTO'),('MARINA'),('MODULO'),('MONTE'),('MORRO'),('NUCLEO'),('PARADA'),
('PARADOURO'),('PARALELA'),('PARQUE'),('PASSAGEM'),('PASSAGEM SUBTERRANEA'),('PASSARELA'),('PASSEIO'),('PATIO'),('PONTA'),('PONTE'),('PORTO'),('PRACA'),('PRACA DE ESPORTES'),
('PRAIA'),('PROLONGAMENTO'),('QUADRA'),('QUINTA'),('RAMAL'),('RAMPA'),('RECANTO'),('RESIDENCIAL'),('RETA'),('RETIRO'),('RETORNO'),('RODO ANEL'),('RODOVIA'),
('ROTATORIA'),('ROTULA'),('RUA'),('RUA DE LIGACAO'),('RUA DE PEDESTRE'),('SERVIDAO'),('SETOR'),('SITIO'),('SUBIDA'),('TERMINAL'),('TRAVESSA'),('TRAVESSA PARTICULAR'),
('TRECHO'),('TREVO')
GO
INSERT LOGRADOURO(LOGRADOURO)
VALUES
('SEBASTIÃO GUÉRCIO'),('DOS IPES'),('DAS ANDORINHAS'),('VICENTE JOSÉ PARISE'),('PRUDENTE DE MORAIS'),('SÃO PAULO'),('CASTELO BRANCO'),('MARIO COVAS'),
('MANOEL DE NÓBREGA'),('RECANTO FELIZ'),('RETIRO DO ENTARDECER')
GO
INSERT INTO BAIRRO(BAIRRO)
VALUES
('SANTA CRUZ'),('ÁREA RURAL'),('CENTRO'),('SANTO ANTÔNIO'),('INOCOP'),('ÁREA INDUSTRIAL'),('JARDIM PARAISO'),('TALAVASSO')
GO
INSERT INTO MUNICIPIO(MUNICIPIO)
VALUES
('TAQUARITINGA'),('SÃO PAULO'),('ARARAQUARA'),('JABOTICABAL'),('MATÃO'),('SÃO CARLOS'),('SÃO JOSÉ DO RIO PRETO'),('MOTUCA'),('ARIRANHA')
GO
INSERT INTO ESTADO(ESTADO,SIGLA_ESTADO)
VALUES
('ACRE','AC'),('AMAPÁ','AP'),('AMAZONAS','AM'),('BAHIA','BA'),('CEARA','CE'),('DISTRITO FEDERAL','DF'),('ESPÍRITO SANTO','ES'),
('GOIÁS','GO'),('MARANHÃO','MA'),('MATO GROSSO','MT'),('MATO GROSSO DO SUL','MS'),('MINAS GERAIS','MG'),('PARÁ','PA'),('PARAÍBA','PB'),('PARANÁ','PR'),
('PERNAMBUCO','PE'),('PIAUÍ','PI'),('RIO DE JANEIRO','RJ'),('RIO GRANDE DO NORTE','RN'),('RIO GRANDE DO SUL','RS'),('RONDÔNIA','RO'),('RORAIMA','RR'),
('SANTA CATARINA','SC'),('SÃO PAULO','SP'),('SERGIPE','SE'),('TOCANTINS','TO')
GO
ALTER TABLE PESSOA
ADD CODIGO_PESSOA_DOMICILIO INT
GO
ALTER TABLE PESSOA
ADD CONSTRAINT FK_CODIGO_PESSOA_DOM FOREIGN KEY(CODIGO_PESSOA_DOMICILIO) REFERENCES DOMICILIO(CODIGO_DOM) ON DELETE CASCADE
GO
SELECT	P.NOME,
		P.SEXO,
		P.RG,
		P.CPF,
		T.DDD,
		T.NUMERO,
		P.ATIVO,		
		TL.TIPO_LOG AS 'TIPO LOGRADOURO',
		L.LOGRADOURO,
		B.BAIRRO,
		M.MUNICIPIO,
		E.ESTADO,
		E.SIGLA_ESTADO AS 'UF'				
FROM PESSOA P 
INNER JOIN TELEFONE_PESSOA T
ON P.CODIGO_P = T.CODIGO_TP_PESSOA
INNER JOIN DOMICILIO D
ON P.CODIGO_PESSOA_DOMICILIO = D.CODIGO_DOM
INNER JOIN TIPO_LOGRADOURO TL
ON D.CODIGO_TIPO_LOG_DOM = TL.CODIGO_TLOG
INNER JOIN LOGRADOURO L
ON D.CODIGO_LOG_DOM = L.CODIGO_LOG
INNER JOIN BAIRRO B
ON D.CODIGO_BAIRRO_DOM = B.CODIGO_BAIRRO
INNER JOIN MUNICIPIO M
ON D.CODIGO_MUNI_DOM = M.CODIGO_MUN
INNER JOIN ESTADO E
ON D.CODIGO_ESTADO_DOM = E.CODIGO_ESTADO
GO
