CREATE TABLE PESSOA(
	CODIGO_P INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL
)
GO

INSERT INTO PESSOA(NOME)
VALUES
('DOUGLAS'),
('JOÃO'),
('PEDRO'),
('ANA'),
('VITÓRIA'),
('AMANDA'),
('HUGO'),
('LUCAS'),
('MARIA'),
('PAULA')
GO
CREATE TABLE TELEFONE_PESSOA(
	CODIGO_TP INT PRIMARY KEY IDENTITY,
	CODIGO_TP_PESSOA INT,
	DDD CHAR(3),
	NUMERO VARCHAR(15),
	
	CONSTRAINT FK_TELEFONE_PESSOA FOREIGN KEY(CODIGO_TP_PESSOA) REFERENCES PESSOA(CODIGO_P) ON DELETE CASCADE
)
GO

INSERT INTO TELEFONE_PESSOA(CODIGO_TP_PESSOA,DDD,NUMERO)
VALUES
(1,'16','9 9748 0797'),
(2,'16','9 9977 6883'),
(3,'17','9 7761 1221'),
(4,'11','9 8811 1231'),
(5,'11','9 8521 1697'),
(6,'17','9 9988 7745'),
(7,'16','9 9519 1334'),
(8,'14','7 4437 7761'),
(9,'14','7 9437 7221'),
(10,'15','6 6443 3548')
GO
ALTER TABLE PESSOA
ADD ATIVO BIT DEFAULT(1)
GO
UPDATE PESSOA
SET ATIVO = 1
WHERE CODIGO_P % 2 = 1
GO
UPDATE PESSOA
SET ATIVO = 0
WHERE CODIGO_P % 2 = 0
GO
ALTER TABLE PESSOA
ADD SEXO CHAR(1)
GO
UPDATE PESSOA
SET SEXO = 'M'
WHERE CODIGO_P = 1
OR
CODIGO_P = 2
OR
CODIGO_P = 3
OR 
CODIGO_P = 7
OR
CODIGO_P = 8
GO
DELETE PESSOA
WHERE CODIGO_P = 6
GO
UPDATE PESSOA
SET SEXO = 'F'
WHERE SEXO IS NULL
GO
SELECT * FROM PESSOA
GO
DELETE FROM PESSOA
WHERE CODIGO_P = 10
GO
SELECT  P.NOME,
		P.ATIVO,
		P.SEXO,
		P.RG,
		P.CPF,
		P.DATA_NASCIMENTO AS 'DATA NASCIMENTO',
		T.DDD,
		T.NUMERO
FROM PESSOA P
INNER JOIN TELEFONE_PESSOA T
ON T.CODIGO_TP_PESSOA = P.CODIGO_P
GO
		
		