CREATE TABLE CARRO(
	CODIGO_CARRO INT PRIMARY KEY IDENTITY,
	MODELO VARCHAR(50) NOT NULL,
	ANO INT NOT NULL,
	COR VARCHAR(50) NOT NULL,
	
	CODIGO_PESSOA_CARRO INT
	CONSTRAINT FK_CODIGO_PESSOA_CARRO FOREIGN KEY(CODIGO_PESSOA_CARRO) REFERENCES PESSOA(CODIGO_P) ON DELETE CASCADE
)
GO
INSERT INTO CARRO(MODELO,ANO,COR,CODIGO_PESSOA_CARRO)
VALUES
('FIAT UNO',2019,'BRANCO',1),('VOLKSWAGEM GOL',2007,'PRETO',2),('FIAT MOBI',2020,'VERMELHO',3),('HONDA CIVIC',2010,'PRATA',4),('TOYOTA COROLLA',2015,'BRANCO',5),
('FORD FIESTA',2009,'CHUMBO',6),('CHEVROLET S10',2010,'PRATA',7),('HYUNDAI HB20',2016,'BRANCO',8),('TOYTA HILUX',2017,'PRATA',9),('FORD FOCUS',2001,'PRETO',10),
('CHEVROLET CRUZE',2016,'BRANCO',14),('CHEVROLET ONIX',2021,'BORDO',17),('JEEP RENEGADE',2022,'BRANCO',19),('FIAT MOBI',2020,'PRATA',20)
GO
SELECT  C.MODELO,
		C.ANO,
		C.COR,
		P.NOME
FROM CARRO C
INNER JOIN PESSOA P
ON C.CODIGO_PESSOA_CARRO = P.CODIGO_P
GO

		
		
		

