CREATE TABLE CLIENTE(
	COD_CLIENTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100),
	RG VARCHAR(20) UNIQUE
)
GO
CREATE TABLE PRODUTO(
	COD_PRODUTO INT PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR(100),
	PRECO DECIMAL(2),
	DATA_VALIDADE SMALLDATETIME
)
GO
CREATE TABLE COMPRA(
	COD_COMPRA INT PRIMARY KEY IDENTITY,
	DATA DATETIME,
	COD_CLIENTE INT,
	VALOR_TOTAL DECIMAL(2),
	
	CONSTRAINT FK_COD_COMPRA_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE) ON DELETE CASCADE	
)
GO
CREATE TABLE ITENS_COMPRA(
	COD_ITEM_COMPRA INT PRIMARY KEY IDENTITY,
	COD_COMPRA INT,
	COD_PRODUTO INT,
	QUANTIDADE INT NOT NULL,
	
	CONSTRAINT FK_COD_IC_COMPRA  FOREIGN KEY(COD_COMPRA)  REFERENCES COMPRA(COD_COMPRA)		ON DELETE CASCADE,
	CONSTRAINT FK_COD_IC_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)	ON DELETE CASCADE	
)
GO
ALTER TABLE PRODUTO
ALTER COLUMN PRECO DECIMAL(18,2)
GO
ALTER TABLE COMPRA
ALTER COLUMN VALOR_TOTAL DECIMAL(18,2)
GO